version: '3.6'
services:  
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      #- 443:443
    volumes:
      - ./nginx/etc/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data:/data:ro
     # - ./cache:/var/cache/nginx:rw